# Generated by Django 3.0.8 on 2021-01-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse_client',
        ),
    ]
