# Generated by Django 3.0.8 on 2021-01-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.ManyToManyField(to='PressingApp.AdresseClient'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='PressingApp.AdresseClient'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_ramassage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ramassage', to='PressingApp.AdresseClient'),
        ),
    ]
