# Generated by Django 3.0.8 on 2021-01-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PressingApp', '0002_remove_client_adresse_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressePretataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('Bp', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('taille', models.CharField(blank=True, choices=[('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('autres', 'autres')], max_length=100, null=True)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(blank=True, choices=[('Femme', 'Femme'), ('Homme', 'Homme'), ('Enfant', 'Enfant'), ('Bebe', 'Bebe')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriePrestataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(blank=True, max_length=100)),
                ('caracteristique', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mode_Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mode', models.CharField(max_length=100)),
                ('caracteristique', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Pack_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prix_Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField()),
                ('pack_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Pack_Article')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(blank=True, choices=[('classique', 'classique'), ('express', 'express'), ('autres', 'autre')], max_length=100)),
                ('caracteristique', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLogistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=100)),
                ('caracteristique', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Article')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='article',
            field=models.ManyToManyField(through='PressingApp.Tarification', to='PressingApp.Article'),
        ),
        migrations.AddField(
            model_name='service',
            name='avis_client',
            field=models.ManyToManyField(through='PressingApp.Note', to='PressingApp.Client'),
        ),
        migrations.AddField(
            model_name='service',
            name='pack_article',
            field=models.ManyToManyField(through='PressingApp.Prix_Pack', to='PressingApp.Pack_Article'),
        ),
        migrations.AddField(
            model_name='prix_pack',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Service'),
        ),
        migrations.CreateModel(
            name='Prestataire_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseigne_juridique', models.CharField(max_length=100)),
                ('numero_imatriculation', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PressingApp.AdressePretataire')),
                ('logistique', models.ManyToManyField(to='PressingApp.Logistique')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Service'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Facture', models.CharField(max_length=12, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PressingApp.BonCommande')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('mode_paiement', models.ManyToManyField(through='PressingApp.BonCommande', to='PressingApp.Mode_Paiement')),
            ],
        ),
        migrations.AddField(
            model_name='boncommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Commande'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='mode_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Mode_Paiement'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie_article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Categorie_Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Type_Article'),
        ),
    ]
