# Generated by Django 3.0.8 on 2021-01-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0002_auto_20210115_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adressepretataire',
            old_name='latitude',
            new_name='latitude_presta',
        ),
        migrations.RenameField(
            model_name='adressepretataire',
            old_name='longitude',
            new_name='longitude_presta',
        ),
    ]
