# Generated by Django 3.0.8 on 2021-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0003_auto_20210118_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressepretataire',
            name='latitude_presta',
            field=models.DecimalField(decimal_places=20, max_digits=199),
        ),
        migrations.AlterField(
            model_name='adressepretataire',
            name='longitude_presta',
            field=models.DecimalField(decimal_places=20, max_digits=199),
        ),
    ]
