# Generated by Django 3.0.8 on 2021-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0004_auto_20210112_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='nom_type',
            field=models.CharField(blank=True, choices=[('entreprise', 'entreprise'), ('personne', 'personne')], max_length=100, null=True),
        ),
    ]
