# Generated by Django 3.0.8 on 2021-01-13 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PressingApp', '0005_auto_20210113_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='typeclient',
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('entreprise', 'entreprise'), ('personne', 'personne')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestataire_service',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestataire_service',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TypeClient',
        ),
    ]
