# Generated by Django 3.0.8 on 2021-01-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0006_auto_20210119_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prestataire',
        ),
        migrations.AddField(
            model_name='commande',
            name='tarification',
            field=models.ManyToManyField(through='PressingApp.Ligne_commande', to='PressingApp.Tarification'),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='tarification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Tarification'),
        ),
    ]
