# Generated by Django 3.0.8 on 2021-01-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0006_auto_20210113_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieprestataire',
            name='nom_categorie',
            field=models.CharField(blank=True, choices=[('blanchisseur', 'blanchisseur'), ('pressing', 'pressing')], max_length=100),
        ),
    ]
