# Generated by Django 3.0.8 on 2021-01-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0007_auto_20210113_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistique',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logistique',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logistique',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logistique',
            name='quartier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logistique',
            name='service',
            field=models.CharField(choices=[('Ramassege', 'Ramassage'), ('Livraison', 'Livraison')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logistique',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
