# Generated by Django 3.0.8 on 2021-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0008_auto_20210122_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire_service',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='prestataire',
            field=models.ManyToManyField(to='PressingApp.Prestataire_Service'),
        ),
    ]
