# Generated by Django 3.0.8 on 2021-01-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0008_auto_20210114_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne_commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriePrestataire',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Client'),
        ),
        migrations.AddField(
            model_name='pack_article',
            name='autre_detailles',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='prestataire_service',
            name='nom_categorie',
            field=models.CharField(blank=True, choices=[('blanchisseur', 'blanchisseur'), ('pressing', 'pressing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prestataire_service',
            name='enseigne_juridique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Commande'),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Prestataire_Service'),
        ),
    ]
