# Generated by Django 3.0.8 on 2021-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0009_auto_20210125_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prestataire',
        ),
        migrations.AddField(
            model_name='prestataire_service',
            name='service',
            field=models.ManyToManyField(to='PressingApp.Service'),
        ),
    ]
