# Generated by Django 3.0.8 on 2021-01-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0010_commande_prestataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='bon_commande',
        ),
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Commande'),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('electronique', 'electronique')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BonCommande',
        ),
        migrations.DeleteModel(
            name='Mode_Paiement',
        ),
    ]
