# Generated by Django 3.0.8 on 2021-01-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0011_auto_20210114_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='status',
        ),
    ]
