# Generated by Django 3.0.8 on 2021-01-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PressingApp', '0013_auto_20210115_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='services',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ligne_commande',
            name='service',
        ),
        migrations.AddField(
            model_name='commande',
            name='prestataire',
            field=models.ManyToManyField(through='PressingApp.Ligne_commande', to='PressingApp.Prestataire_Service'),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PressingApp.Prestataire_Service'),
        ),
    ]
