# Generated by Django 3.0.8 on 2021-01-15 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PressingApp', '0014_auto_20210115_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestataire_Service',
            new_name='Prestataire',
        ),
    ]
